// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cnetwork

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfCnetworkEvent struct {
	Timestamp uint64
	Pid       uint32
	Comm      [16]uint8
	Cid       [12]uint8
	Flag      uint8
	_         [3]byte
	Daddr     uint32
	Dport     uint16
	_         [2]byte
	Saddr     uint32
	Sport     uint16
	_         [6]byte
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	KprobeTcpTransmitSkb  *ebpf.ProgramSpec `ebpf:"kprobe_tcp_transmit_skb"`
	KprobeTcpV4DoRcv      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v4_do_rcv"`
	KretprobeSockAllocRet *ebpf.ProgramSpec `ebpf:"kretprobe_sock_alloc_ret"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CnetworkBanned *ebpf.MapSpec `ebpf:"cnetwork_banned"`
	ContainernetRb *ebpf.MapSpec `ebpf:"containernet_rb"`
	Socktable      *ebpf.MapSpec `ebpf:"socktable"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CnetworkBanned *ebpf.Map `ebpf:"cnetwork_banned"`
	ContainernetRb *ebpf.Map `ebpf:"containernet_rb"`
	Socktable      *ebpf.Map `ebpf:"socktable"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CnetworkBanned,
		m.ContainernetRb,
		m.Socktable,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	KprobeTcpTransmitSkb  *ebpf.Program `ebpf:"kprobe_tcp_transmit_skb"`
	KprobeTcpV4DoRcv      *ebpf.Program `ebpf:"kprobe_tcp_v4_do_rcv"`
	KretprobeSockAllocRet *ebpf.Program `ebpf:"kretprobe_sock_alloc_ret"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.KprobeTcpTransmitSkb,
		p.KprobeTcpV4DoRcv,
		p.KretprobeSockAllocRet,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
