package cnetwork

import (
	"bytes"
	"ebpf_exporter/event"
	"encoding/binary"
	"errors"
	"log"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"golang.org/x/sys/unix"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target amd64 -type cnetwork_event bpf ../../kern/containernet.c -- -I../../kern/headers
func InitCNetwork(stopper <-chan struct{}, eventCh chan<- event.IEvent) {
	// Load pre-compiled programs and maps into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()
	kretp, err := link.Kretprobe("sock_alloc", objs.KretprobeSockAllocRet, nil)
	if err != nil {
		log.Fatalf("opening kretprobe: %s", err)
	}
	defer kretp.Close()
	kp1, err := link.Kprobe("__tcp_transmit_skb", objs.KprobeTcpTransmitSkb, nil)
	if err != nil {
		log.Fatalf("opening kprobe: %s", err)
	}
	defer kp1.Close()
	kp2, err := link.Kprobe("tcp_v4_do_rcv", objs.KprobeTcpV4DoRcv, nil)
	if err != nil {
		log.Fatalf("opening kprobe: %s", err)
	}
	defer kp2.Close()

	rd, err := ringbuf.NewReader(objs.ContainernetRb)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %s", err)
	}
	defer rd.Close()
	log.Println("Waiting for cnetwork events..")

	go func() {
		// bpfEvent is generated by bpf2go.
		var bpfevent bpfCnetworkEvent
		for {
			record, err := rd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					log.Println("Received signal, exiting..")
					return
				}
				log.Printf("reading from reader: %s", err)
				continue
			}
			// Parse the ringbuf event entry into a bpfEvent structure.
			if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &bpfevent); err != nil {
				log.Printf("parsing ringbuf event: %s", err)
				continue
			}
			if bpfevent.Saddr == 0 || bpfevent.Daddr == 0 {
				continue //脏数据
			}
			// 打印 bpfEvent 结构体的内容
			syscallEvent := event.CNetwork_event{
				Type:      "Network_event",
				Timestamp: bpfevent.Timestamp,
				Pid:       bpfevent.Pid,
				Comm:      unix.ByteSliceToString(bpfevent.Comm[:]),
				Cid:       unix.ByteSliceToString(bpfevent.Cid[:]),
				Flag:      bpfevent.Flag,
				Daddr:     [4]byte{byte(bpfevent.Daddr), byte(bpfevent.Daddr >> 8), byte(bpfevent.Daddr >> 16), byte(bpfevent.Daddr >> 24)},
				Dport:     bpfevent.Dport,
				Saddr:     [4]byte{byte(bpfevent.Saddr), byte(bpfevent.Saddr >> 8), byte(bpfevent.Saddr >> 16), byte(bpfevent.Saddr >> 24)},
				Sport:     bpfevent.Sport,
			}
			eventCh <- syscallEvent
		}
	}()

	<-stopper
}
