package csyscall

import (
	"bytes"
	"ebpf_exporter/event"
	"encoding/binary"
	"errors"
	"log"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"golang.org/x/sys/unix"
)

//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -target amd64 -type syscall_event -type syscallcntkey bpf ../../kern/syscall.c -- -I../../kern/headers
const TICKER = 5

func InitSyscall(stopper <-chan struct{}, eventCh chan<- event.IEvent) {
	// Load pre-compiled programs and maps into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	tp_enter, err := link.AttachTracing(link.TracingOptions{
		Program:    objs.SysEnter,
		AttachType: ebpf.AttachTraceRawTp,
	})
	if err != nil {
		log.Fatalf("attaching raw tracepoint: %v", err)
	}
	defer tp_enter.Close()

	tp_exit, err := link.AttachTracing(link.TracingOptions{
		Program:    objs.SysExit,
		AttachType: ebpf.AttachTraceRawTp,
	})
	if err != nil {
		log.Fatalf("attaching raw tracepoint: %v", err)
	}
	defer tp_exit.Close()

	rd, err := ringbuf.NewReader(objs.SyscallRb)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %s", err)
	}
	defer rd.Close()

	log.Println("Waiting for tcp events..")

	// Read from the ringbuf
	go func() {
		// bpfEvent is generated by bpf2go.
		var bpfevent bpfSyscallEvent
		for {
			record, err := rd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					log.Println("Received signal, exiting..")
					return
				}
				log.Printf("reading from reader: %s", err)
				continue
			}
			// Parse the ringbuf event entry into a bpfEvent structure.
			if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &bpfevent); err != nil {
				log.Printf("parsing ringbuf event: %s", err)
				continue
			}
			// 打印 bpfEvent 结构体的内容
			syscallEvent := event.Syscall_event{
				Timestamp: bpfevent.Timestamp,
				Flag:      bpfevent.Flag,
				Pid:       bpfevent.Pid,
				Comm:      unix.ByteSliceToString(bpfevent.Comm[:]),
				Syscall:   bpfevent.SyscallId,
				Ret:       bpfevent.Ret,
				Cid:       unix.ByteSliceToString(bpfevent.Cid[:]),
				Info:      unix.ByteSliceToString(bpfevent.Info[:]),
			}
			eventCh <- syscallEvent
		}
	}()
	// Read from the array
	go func() {
		ticker := time.NewTicker(TICKER * time.Second)
		defer ticker.Stop()
		for range ticker.C {
			var (
				key   bpfSyscallcntkey
				value uint64
			)
			iner := objs.SyscallCnt.Iterate()
			for iner.Next(&key, &value) {
				eventCh <- event.Syscall_event{
					Timestamp: uint64(time.Now().Unix()),
					Flag:      2,
					Pid:       key.Pid,
					Comm:      unix.ByteSliceToString(key.Comm[:]),
					Syscall:   key.SyscallId,
					Ret:       int64(value),
					Cid:       unix.ByteSliceToString(key.Cid[:]),
				}
			}
		}
	}()

	<-stopper
	log.Println("Stopping syscall")
}
