global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ebpf"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.31.172:2024"]

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets: ["192.168.31.68:8000"]
